[package]
name = "sp800-90b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
group = "0.13.0"
mathru = "0.14.0"
